- README.md
- checkup.go
- fs.go
- fs_test.go
- statuspage/index.html
- statuspage/js/fs.js
> Adds local filesystem support

- .travis.yml
- httpchecker.go
This pull request will allow the HTTP status of redirects to be checked, without following the redirect.
This way, a redirect can be considered healthy, by configuring `"up_status": 302` or `"up_status": 301` in checkup.json.
For unchanged checkup.json configurations, redirects will still fail as before (as they are not HTTP status 2xx, the default expected).
> Do not fail on HTTP redirects, but do not follow them either, close #22.

- checkup.go
- cmd/root.go
Quick PR to add colors to `checkup` status CLI message and exit with status 1 when not all checks are healthy (for use in CI scripts):
> Colors and exit status

- httpchecker.go
- httpchecker_test.go
This adds support for adding customer request headers to HTTPChecker. It adds a new field Headers to the HTTPChecker type. The Headers field is a slice of type Header, which has fields for the name and value of the header.
> Add support for HTTP Headers

- README.md
If you're creating an S3 bucket manually, you need to make sure the region is US Standard, and this is also a requirement in the configuration of the storage.
> Updated to include required US region

- README.md
On Ubuntu 16.04. with docker 1.11.1 there is an issue accessing github.com from docker.
Fixes #39
> documentation: added docker parameter to fix build issue

- statuspage/js/statuspage.js
Changes on the front-end only, compatibility with IE 11.
For some reason IE 11 is able to get to checkup.dom.lastcheck.innerHTML before DOMContentLoaded event. Moving when getChecksWithin is invoked remedies that situation.
Performance doesn't seem to be affected.
http://caniuse.com/#search=remove ChildNode.remove() not compatible with IE 11.
> statuspage: .innerHTML undefined on dom.lastcheck, .remove() undefined

- s3.go
This change only configures credentials for the S3 client if AcccessKeyID and SecretAccessKey have both been set in the config. Otherwise it falls back to the default credential lookup mechanism in the AWS SDK which tries to aquire credentials from environment variables or EC2 metadata. This allows checkup to be used without providing explicit credentials on an EC2 machine with an appropriate instance profile.
> allow empty S3 creds for config from EC2 metadata

- cmd/root.go
- logger.go
In https://github.com/sourcegraph/checkup/pull/54, @mholt mentioned that allowing the possibility of logging would be nice. I agree.
This PR turns logging off by default (by sending logs to `ioutil.Discard`), with the ability to enable it via the `-v` flag.
> Logging: provide command-line control

- checkup.go
- github.go
- github_test.go
Closes #53.
[See it in action.](https://www.parkermoore.de/status/) ([repo](https://github.com/parkr/status)).
This is *very* rough and undocumented code. It makes a number of GitHub REST API requests to push JSON files; it's modeled off the `FS` provider. The testing code is similarly modeled after the `FS` provider's texts. I basically implement the 4 endpoints I use in a test server and keep a "git repo" and index in memory. 😆 
I expect this code to evolve & drastically improve with your input.
Configuration is as follows (all fields presently required):
```json
{
"storage": {
"provider": "github",
"access_token": "some_api_access_token_with_repo_scope",
"repository_owner": "owner",
"repository_name": "repo",
"committer_name": "User Name",
"committer_email": "username@example.com", …
```
> Add GitHub storage provider

- checkup.go
checkup adds ANSI escape sequences to have a user-friendly output on the command line.
However, this is not helpful when used as a library.
The patch included in this PR adds a DisableColor helper function that can be called in order to disable the terminal colors sequences.
> Add DisableColor() to disable colors in string formating

- checkup.go
- fs.go
- fs_test.go
- github.go
Add Fetch and GetIndex to the Storage interface.
This enables the library to be used not only to save records
but also to read them back.
The FS backend is implemented, the Github backend is updated but not
tested, and the S3 has dummy handlers that currently return a "not-implemented"
error.
The idea is to be able to use checkup to read existing data instead of duplicating the code.
> Extend Storage interface

- README.md
- checkup.go
- sql.go
- sql_test.go
Would you consider merging SQL storage?
This patchs adds a SQL storage implementation.
Only the sqlite3 is available, but any backend supported by the sqlx package should be easily added.
> SQL storage support

- CONTRIBUTING.md
- README.md
bump to 1.8 and increase chance of success for simpler docker example.
Fixes #75
> docs: bump golang version

- README.md
GitHub does not support highlighting `json` natively. The workaround rather is to use either `js` or none at all.
This PR aims to improve the readability by addressing the weird red blocks in the syntax highlighting.
> docs: update readme for better highlighting

- CONTRIBUTING.md
- README.md
This PR updates the documentation to reflect the requirement of Golang v1.10, up from v1.8.
A recent attempt to build the project resulted in some errors:
```sh
$ go version 
go version go1.9.4 darwin/amd64
$ go build -v -ldflags '-s' -o ../../checkup
github.com/miekg/dns
../../../github.com/miekg/dns/dnssec_keyscan.go:290:7: undefined: strings.Builder
../../../github.com/miekg/dns/msg_helpers.go:271:8: undefined: strings.Builder
../../../github.com/miekg/dns/serve_mux.go:43:9: undefined: strings.Builder
../../../github.com/miekg/dns/types.go:440:10: undefined: strings.Builder
../../../github.com/miekg/dns/types.go:464:10: undefined: strings.Builder
../../../github.com/miekg/dns/types.go:492:10: undefined: strings.Builder
../../../github.com/miekg/dns/types.go:513:29: undefined: …
```
> Updating docs Go version to 1.10

- statuspage/js/fs.js
On GitHub Pages the files are often so good cached that old / stale data
is still retrieved and not the latest version of `index.json`.
Even a reload with the "disable cache" option enabled in the network
settings of the browser developer tools does not help in most cases.
Thus we have to bust the cache for every load by adding a timestamp in
this case.
There are also other solutions but these would affect all AJAX calls and
this solution busts the cache for only the `index.json` file.
This PR closes #117
> scripts: add timestamp to bust the cache to retrieve latest updates

- CONTRIBUTING.md
- DCO
We currently ask external contributors to sign a CLA, but many open-source projects opt for a DCO instead (e.g., https://about.gitlab.com/blog/2017/11/01/gitlab-switches-to-dco-license/).
This adds a DCO to this repository, which will allow us to merge PRs from external contributors without first asking them to sign a CLA.
> add DCO file for external contributors

- storage/appinsights/appinsights.go
- storage/appinsights/appinsights_test.go
- Change time.Duration fields to `int`
- Remove duplicate code
> Resolve issues from #132

- README.md
- storage/github/github.go
- storage/github/github_test.go
Adding '[ci skip]' made sense in the original implementation, when CI
was not often used to act on a status repo. In the age of GitHub
Actions, it would be helpful to be able to control whether this string
is appended.
The current implementation gives the user the choice to append it by
setting the `"commit_message_suffix": "[ci skip]"` field to their
configuration, but leaves it off by default.
> storage/github: add commit_message_suffix as config entry

- storage/github/github.go
In order to be a Maintainer, the GitHub Storage implementation must respond to `Maintain()`. Unlike all the other implementations, the GitHub implementation's Maintain() method was on the pointer receiver. This fix should allow the GitHub Storage implementation to be a Maintainer.
As a side note, it'd be nice to have a setting for this somewhere in case someone wants to keep all their history.
> github: make it a Maintainer
